maddogg91/study-buddy

- SystemRequirements.md
Document without priority chart. Please merge, pull from main into your branch and add priorities to this document.
> Add SRS doc

- SystemRequirements.md
grammatical changes and clarification
> Rechecking 2.2

- SystemRequirements.md
> Sam branch

- SystemRequirements.md
> Cierra branch

- milestone.md
> Answers to MVP questions.

- milestone.md
What features or additional engineering work will it take to get you to a project you’d be comfortable inviting other people to use?
> Question 2

- milestone.md
> Question 3: stretch goals

- milestone.md
If you are behind schedule, what items on the roadmap will you de-prioritize? -Calendar
-Zoom 
-Matchmaking Quiz
-Tags
> Final Question

- main.py
- templates/createGroup.html
- templates/currentConvo.html
- templates/existingGroups.html
- templates/home.html
- templates/index.html
- templates/login.html
- templates/settings.html
- templates/signUp.html
Index.html serves as the first page from figma which offers 2 tabs of sign up or login as an existing user. If you have any questions on what html files are which screen please ask
> Added html files and routes with links

- db.py
- main.py
I've added connection to mongo db and a test route def -login to test default user in the db "test", "test".
> basic db impl

- db.py
- main.py
- templates/signUp.html
Added login change to user table instead of registration table. Added alert to signup page. Fixed signup module error, redirects to home.html instead. Added a flag to check if user's session is active in main.py, users should not be able to navigate to home page unless logged in. Please ensure flag is active for pages that require user login.
> user login update

- db.py
- main.py
- templates/login.html
Google sign in/up implementation
This feature adds a new db lookup to googleUsers or an insert if a user signs up for the first time.
Added button to login.html
Removed unnecessary code and fixed session issues.
> Google implementation

- db.py
- main.py
Reworked some of the google sign in and sign up code. Google users should now save correctly in db.
> google-sign-in fix

- templates/results.html
> Join Card Photo fix

- README.md
Do we need Screenshots? or any added information?
> Updated MVP readMe

- db.py
- groupmsg.py
- main.py
- templates/existingGroups.html
Added send messages from front end to back end for first chat
Issue: other chats won't pick up event function will investigate.
Sync messages after refresh, needs autoupdate logic 
Profile picture and sender name attached to messages.
> sync messages pt1

- main.py
> removed flask

- .pylintrc
- Group.py
- db.py
- enc.py
- groupmsg.py
- main.py
Pylint for code existing in our root project folder
TODO:
>Lint test folder
>Lint unit-tests
> code clean up

- templates/existingGroups.html
Added temporary message in place of load times for group messages being sent and received from server to client.
> changes to temp messages

- main.py
- templates/profile.html
> fixed quiz button

- static/search.css
- templates/results.html
creating spacing, background margin, and font size changes so that cards are not squished together!
> pretty join cards with space

- static/search.css
- templates/results.html
Reverts maddogg91/study-buddy#114
> Revert "pretty join cards with space"

- templates/results.html
creating spacing, background margin, and font size changes so that cards are not squished together!
> pretty join cards

- templates/profile.html
> cleaned up profile
